  properties([
        parameters([
      string(name: 'Cluster', defaultValue: 'ncp3-pvt', description: null),
      string(name: 'region', defaultValue: 'us-east-1', description: null),
      text(name: 'baseJson', defaultValue: null, description: null)
        ])
])
pipeline {
  agent any

  stages {
    stage('Checkout Scm') {
      steps {
        git 'https://github.com/folio-org/perf-testing'
      }
    }

    stage('Build Artifact') {
      steps {
        sh '''cd common/ECSResourcesCheck
              mvn clean install
           '''
      }}

    stage('Compare ECS clusters') {
      steps {
        withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'aws_folio_int', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']]){
            script {
                def profile = 'int'
                sh '''cd common/ECSResourcesCheck/target
                java -jar ECSClusterComparison-1.0-SNAPSHOT-jar-with-dependencies.jar ${Cluster} ${AWS_ACCESS_KEY_ID} ${AWS_SECRET_ACCESS_KEY} ${region} "${baseJson}"
                '''
            }
        }
      }
    }
  }
}