  properties([
        parameters([
      string(name: 'Cluster', defaultValue: 'ncp3-pvt', description: null),
      string(name: 'aws_access_key_id', defaultValue: null, description: null),
      string(name: 'aws_secret_access_key', defaultValue: null, description: null),
      string(name: 'region', defaultValue: 'us-east-1', description: null),
      text(name: 'baseJson', defaultValue: null, description: null)
        ])
])
pipeline {
  agent any

  stages {
    stage('Checkout Scm') {
      steps {
        git 'https://github.com/folio-org/perf-testing'
      }
    }

    stage('Build Artifact') {
      steps {
        sh '''cd common/ECSResourcesCheck
              mvn clean install
           '''
      }}

    stage('Compare ECS clusters') {
      steps {
      withCredentials([usernamePassword(credentialsId: 'aws_folio_int', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
      sh '''cd common/ECSResourcesCheck/target
            echo  ${USERNAME}
            echo ${PASSWORD}
            java -jar AWSFin-1.0-SNAPSHOT-jar-with-dependencies.jar ${Cluster} ${USERNAME} ${PASSWORD} ${region} "${baseJson}"
         '''
         }}

    }
  }}