  properties([
        parameters([
      string(name: 'Cluster', defaultValue: 'ncp3-pvt', description: null),
      string(name: 'aws_access_key_id', defaultValue: null, description: null),
      string(name: 'aws_secret_access_key', defaultValue: null, description: null),
      string(name: 'region', defaultValue: 'us-east-1', description: null),
      text(name: 'baseJson', defaultValue: null, description: null)
        ])
])
pipeline {
  agent any

  stages {
    stage('Checkout Scm') {
      steps {
        git 'https://github.com/folio-org/perf-testing'
      }
    }

    stage('Build Artifact') {
      steps {
        sh '''cd common/ECSResourcesCheck
              mvn clean install
           '''
      }}

    stage('Compare ECS clusters') {
      steps {
          script{
            def profile ='int'
            def secretkey = sh([script: "aws configure get aws_secret_access_key --profile ${profile} | xargs echo -n", returnStdout: true])
            def publickey = sh([script:"aws configure get aws_access_key_id --profile ${profile} | xargs echo -n",returnStdout: true])
          sh """cd common/ECSResourcesCheck/target
                java -jar ECSClusterComparison-1.0-SNAPSHOT-jar-with-dependencies.jar ${Cluster} ${publickey} ${secretkey} ${region} "${baseJson}"
         """
         }}

    }
  }}