{
 "title": "Performance Comparison Dashboard",
 "tags": [ "benchmark" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "request_name",
    "label": "Request name",
    "query": "SHOW TAG VALUES FROM api_comparison WITH KEY = \"request_name\" WHERE \"simulation\" =~ /^$simulation$/"
   },
   {
    "name": "calculation",
    "label": "Calculation",
    "query": "min, mean, max, pct50, pct75, pct90, pct95, pct99"
   },
   {
    "name": "simulation",
    "label": "Simulation",
    "query": "SHOW TAG VALUES FROM api_comparison WITH KEY = \"simulation\""
   },
   {
    "name": "user_count",
    "label": "User count",
    "query": "SHOW TAG VALUES FROM api_comparison WITH KEY = \"users\" WHERE simulation =~ /^$simulation$/"
   },
   { "name": "db_url", "query": "http://carrier-influx" },
   { "name": "perf_host", "query": "http://carrier-influx" },
   {
    "name": "duration",
    "label": "Duration",
    "query": "SHOW TAG VALUES FROM api_comparison WITH KEY = \"duration\""
   },
   { "name": "grouping", "query": "1s,10s,30s,1m,3m,5m,10m,30m,1h" },
   {
    "name": "build1",
    "label": "Build One",
    "query": "SHOW TAG VALUES FROM api_comparison WITH KEY = \"build_id\" WHERE simulation =~ /^$simulation$/"
   },
   {
    "name": "build2",
    "label": "Build Two",
    "query": "SHOW TAG VALUES FROM api_comparison WITH KEY = \"build_id\" WHERE simulation =~ /^$simulation$/"
   },
   { "name": "db_name", "query": "comparison" }
  ]
 },
 "panels": [
  {
   "title": "Response time over time for $simulation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms", "label": "Response Time" }
   ],
   "targets": [
    {
     "alias": "$tag_request_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean($calculation) FROM api_comparison WHERE simulation = '$simulation' AND \"request_name\" =~ /^$request_name$/  AND $timeFilter GROUP BY time($grouping), \"request_name\" fill(null)",
     "select": [
      [
       { "params": [ "$calculation" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 0 },
   "content": "<script>\n\n    MARKED_BUILD = ''\n    EPOCH = \"ms\";\n\n    function getVar(varName, onAllEmpty = true) {\n        var vars = angular.element('dashboard-submenu').injector().get('variableSrv').variables;\n        var result = []; vars.forEach(function (variable) {\n            if (variable.name == varName) {\n                if (variable.options[0].value == \"$__all\"\n                    && variable.options[0].selected) {\n                    if (onAllEmpty) { return []; } else {\n                        for (var i = 1; i < variable.options.length; i++) {\n                            result.push(variable.options[i].value);\n                        } return result\n                    }\n                } else {\n                    variable.options.forEach(function (option) { if (option.selected) { result.push(option.value); } });\n                }\n            };\n        }); return result\n    };\n\n    function formatDataset(data) {\n        rows = [];\n        results = data.results;\n        results.forEach(function (result, i) {\n            series = result.series;\n            if (series != undefined) {\n                series.forEach(function (serie) {\n                    var keys = serie.columns;\n                    var values = serie.values;\n                    values.forEach(function (value) {\n                        var row = {};\n                        value.forEach(function (val, v) {\n                            row[keys[v]] = val != null ? val : 0;\n                        })\n                        rows.push(row);\n                    });\n                });\n            }\n        });\n        return rows\n    }\n\n    function getBuildData(build_id) {\n        var result = []\n        var query = `select * from api_comparison where build_id='${build_id}'`\n\n        $.ajax({\n            type: \"GET\",\n            url: '/grafana/api/datasources/proxy/3/query',\n            async: false,\n            data: { q: query, db: \"comparison\", epoch: EPOCH },\n            success: function (data) {\n                result = formatDataset(data)\n            },\n            error: function (json, code) {\n                console.log(\"Some error occured: \")\n                console.error(json)\n            }\n        });\n\n        return result;\n    }\n\n    function checkBaselineData(build_id) {\n        var result = []\n        var query = `select * from api_comparison where build_id='${build_id}' limit 1`\n\n        $.ajax({\n            type: \"GET\",\n            url: '/grafana/api/datasources/proxy/3/query',\n            async: false,\n            data: { q: query, db: \"comparison\", epoch: EPOCH },\n            success: function (data) {\n                result = formatDataset(data)\n            },\n            error: function (json, code) {\n                console.log(\"Some error occured: \")\n                console.error(json)\n            }\n        });\n\n        return result;\n    }\n\n    function getCurrentBaseline(simulation) {\n        var result = ''\n        var query = `select last(pct95), build_id from api_comparison where \"simulation\"='${simulation}' and \"build_id\" =~ /^audit/ limit 1`\n\n        $.ajax({\n            type: \"GET\",\n            url: '/grafana/api/datasources/proxy/3/query',\n            async: false,\n            data: { q: query, db: \"comparison\", epoch: EPOCH },\n            success: function (data) {\n                data = formatDataset(data)\n                if (data[0]) {\n                    result = data[0]['build_id']\n                }\n            },\n            error: function (json, code) {\n                console.log(\"Some error occured: \")\n                console.error(json)\n            }\n        });\n\n        return result;\n    }\n\n    function postBaselineBuild() {\n        var url = '/grafana/api/datasources/proxy/3/write?db=comparison'\n        var simulation = getVar('simulation')\n        var marked_build_id = MARKED_BUILD\n        var data = getBuildData(marked_build_id)\n        var build_id = 'audit_' + simulation + '_' + MARKED_BUILD\n        var build_check = checkBaselineData(build_id)\n        if (build_check.length > 0) {\n            alert(`Build has already marked as '${build_id}'.`)\n        } else {\n            if (data.length != 0) {\n                data.forEach(function (request) {\n                    var write_data = `api_comparison,simulation=${request.simulation},users=${request.users},test_type=${request.test_type},build_id=${build_id},request_name=${request.request_name},method=${request.method},duration=${request.duration} `\n                        + `throughput=${request.throughput},total=${request.total},ok=${request.ok},ko=${request.ko},1xx=${request['1xx']},2xx=${request['2xx']},3xx=${request['3xx']},4xx=${request['4xx']},5xx=${request['5xx']},NaN=${request.NaN}`\n                        + `,min=${request.min},max=${request.max},mean=${request.mean},pct50=${request.pct50},pct75=${request.pct75},pct90=${request.pct90},pct95=${request.pct95},pct99=${request.pct99} ${request.time}`\n                    $.ajax({\n                        type: \"POST\",\n                        url: url,\n                        contentType: \"application/octet-stream\",\n                        async: false,\n                        data: write_data,\n                        success: function (json) {\n                            console.log('Saved.')\n                        },\n                        error: function (json, code) {\n                            console.log(json)\n                        }\n                    });\n                })\n                alert(`Bulid '${MARKED_BUILD}' marked as '${build_id}'`)\n            } else {\n                alert('No data for selected build id.')\n            }\n        }\n        return false;\n    }\n\n    function getBuildName() {\n        var select = document.getElementById(\"select_build\")\n        MARKED_BUILD = select.options[select.selectedIndex].text\n    }\n\n    function showCurrentBaseline(simulation) {\n        var baseline = getCurrentBaseline(simulation)\n        var container = $('#current_baseline')\n        if (baseline != '') {\n            container.html(`Current baseline is: <br /><b>${baseline}</b>`)\n        } else {\n            container.html(`Baseline for '${simulation}' simulation not yet set.`)\n        }\n\n    }\n\n    function waitForRefresh() {\n        try {\n            $('#select_build').remove()\n            var select = $('<select>').attr('id', 'select_build').attr('onchange', 'getBuildName()').attr('width', '100%')\n            var simulation = getVar('simulation')\n            var build1 = getVar('build1')\n            var build2 = getVar('build2')\n            var option_1 = $('<option>').text(build1).attr('value', 'build_1')\n            var option_2 = $('<option>').text(build2).attr('value', 'build_2')\n\n            select.append(option_1)\n            select.append(option_2)\n            $('#build_ids').append(select)\n\n            showCurrentBaseline(simulation)\n        } catch (err) {\n            console.log(err)\n        }\n    }\n\n    $(document).ready(function () {\n        waitForRefresh();\n        getBuildName();\n    });\n    angular.element('grafana-app').injector().get('$rootScope').$on('refresh', function () { waitForRefresh(); getBuildName(); });\n\n</script>\n<style>\n    #mark_button {\n        background-color: #00678b;\n        color: white;\n        border: 2px solid #00678b;\n        border-radius: 4px;\n    }\n\n    #mark_button:hover {\n        background-color: #04b3f8;\n    }\n</style>\n\nPlease select build to mark as baseline:\n<div id='build_ids'></div>\n<br />\n<input type=\"button\" id='mark_button' onclick=\"postBaselineBuild()\" value=\"Mark as baseline\" />\n<br />\n<div id='current_baseline'></div>"
  },
  {
   "title": "Response Codes for $simulation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Quantity" }
   ],
   "targets": [
    {
     "alias": "1xx",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(/1xx$/) FROM api_comparison WHERE simulation = '$simulation'  AND \"request_name\" =~ /^$request_name$/ AND $timeFilter GROUP BY time($grouping) fill(null)",
     "select": [
      [
       { "params": [ "$calculation" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "2xx",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(/2xx$/) FROM api_comparison WHERE simulation = '$simulation' AND \"request_name\" =~ /^$request_name$/  AND $timeFilter GROUP BY time($grouping) fill(null)",
     "select": [
      [
       { "params": [ "$calculation" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "3xx",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(/3xx$/) FROM api_comparison WHERE simulation = '$simulation' AND \"request_name\" =~ /^$request_name$/  AND $timeFilter GROUP BY time($grouping) fill(null)",
     "select": [
      [
       { "params": [ "$calculation" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "4xx",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(/4xx$/) FROM api_comparison WHERE simulation = '$simulation' AND \"request_name\" =~ /^$request_name$/  AND $timeFilter GROUP BY time($grouping) fill(null)",
     "select": [
      [
       { "params": [ "$calculation" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "5xx",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(/5xx$/) FROM api_comparison WHERE simulation = '$simulation' AND \"request_name\" =~ /^$request_name$/  AND $timeFilter GROUP BY time($grouping) fill(null)",
     "select": [
      [
       { "params": [ "$calculation" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "NaN",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(/NaN$/) FROM api_comparison WHERE simulation = '$simulation' AND \"request_name\" =~ /^$request_name$/  AND $timeFilter GROUP BY time($grouping) fill(null)",
     "select": [
      [
       { "params": [ "$calculation" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Failures",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(/ko$/) FROM api_comparison WHERE simulation = '$simulation' AND \"request_name\" =~ /^$request_name$/  AND $timeFilter GROUP BY time($grouping) fill(null)",
     "select": [
      [
       { "params": [ "$calculation" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Response code breakdown",
   "type": "table",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"sum_1xx1\" AS \"1xx t1\", \"sum_1xx2\" AS \"1xx t2\", \"sum_2xx1\" AS \"2xx t1\", \"sum_2xx2\" AS \"2xx t2\",         \"sum_3xx1\" AS \"3xx t1\", \"sum_3xx2\" AS \"3xx t2\", \"sum_4xx1\" AS \"4xx t1\", \"sum_4xx2\" AS \"4xx t2\",         \"sum_5xx1\" AS \"5xx t1\", \"sum_5xx2\" AS \"5xx t2\", \"sum_NaN1\" AS \"NaN t1\", \"sum_NaN2\" AS \"NaN t2\"           FROM (SELECT sum(*) FROM \t(SELECT sum(\"1xx\"::float) AS \"1xx1\", sum(\"2xx\"::float) AS \"2xx1\",      \t\t         sum(\"3xx\"::float) AS \"3xx1\", sum(\"4xx\"::float) AS \"4xx1\", \t\t\t         sum(\"5xx\"::float) AS \"5xx1\", sum(\"NaN\"::float) AS \"NaN1\"  \t\t\t         from api_comparison where build_id = '$build1' AND \"request_name\" =~ /^$request_name$/), \t         (SELECT sum(\"1xx\"::float) AS \"1xx2\", sum(\"2xx\"::float) AS \"2xx2\",      \t\t         sum(\"3xx\"::float) AS \"3xx2\", sum(\"4xx\"::float) AS \"4xx2\", \t\t\t         sum(\"5xx\"::float) AS \"5xx2\", sum(\"NaN\"::float) AS \"NaN2\"  \t\t\t         from api_comparison where build_id = '$build2' AND \"request_name\" =~ /^$request_name$/) ) GROUP BY request_name",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Diff by $calculation",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 18 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT ((\"sum_check2\"-\"sum_check1\")/\"sum_check2\")*100 FROM (SELECT sum(*) FROM (SELECT mean(\"$calculation\"::float) AS \"check1\" from api_comparison where build_id = '$build1'), (SELECT mean(\"$calculation\"::float) AS \"check2\" from api_comparison where build_id = '$build2') )",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "comparison of $build1 and $build2",
   "type": "table",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 18 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"sum_First Total\" AS \"Total Req t1\", \"sum_Second Total\" AS \"Total Req t2\",          \"sum_First Min\" AS \"Min t1\", \"sum_Second Min\" AS \"Min t2\",         \"sum_First PCT95\" AS \"Pct95 t1\", \"sum_Second PCT95\" AS \"Pct95 t2\",  \t    \"sum_First Max\" AS \"Max t1\", \"sum_Second Max\" AS \"Max t2\", \t    \"sum_First Success\" AS \"Success t1\", \"sum_Second Success\" AS \"Success t2\",  \t    \"sum_First Failed\" AS \"Failed t1\", \"sum_Second Failed\" AS \"Failed t2\"  FROM (SELECT sum(*) from \t(SELECT sum(\"total\"::float) AS \"First Total\", mean(\"min\"::float) AS \"First Min\",      \t\t mean(\"pct95\"::float) AS \"First PCT95\", mean(\"max\"::float) AS \"First Max\",  \t\t\t sum(\"ok\"::float) AS \"First Success\", sum(\"ko\"::float) AS \"First Failed\"  \t\t\t from api_comparison where build_id = '$build1' AND \"request_name\" =~ /^$request_name$/), \t (SELECT sum(\"total\"::float) AS \"Second Total\", mean(\"min\"::float) AS \"Second Min\",      \t\t mean(\"pct95\"::float) AS \"Second PCT95\", mean(\"max\"::float) AS \"Second Max\",  \t\t\t sum(\"ok\"::float) AS \"Second Success\", sum(\"ko\"::float) AS \"Second Failed\"  \t\t\t from api_comparison where build_id = '$build2' AND \"request_name\" =~ /^$request_name$/) ) GROUP BY request_name",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Percentile comparison for $build1 and $build2",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"sum_pct501\" AS \"p50 t1\", \"sum_pct502\" AS \"p50 t2\",         \"sum_pct751\" AS \"p75 t1\", \"sum_pct752\" AS \"p75 t2\", \t    \"sum_pct901\" AS \"p90 t1\", \"sum_pct902\" AS \"p90 t2\", \t    \"sum_pct951\" AS \"p95 t1\", \"sum_pct952\" AS \"p95 t2\", \t    \"sum_pct991\" AS \"p99 t1\", \"sum_pct992\" AS \"p99 t2\" FROM (SELECT sum(*) FROM \t (SELECT mean(\"pct50\"::float) AS \"pct501\", mean(\"pct75\"::float) AS \"pct751\",      \t\t mean(\"pct90\"::float) AS \"pct901\", mean(\"pct95\"::float) AS \"pct951\", \t\t\t mean(\"pct99\"::float) AS \"pct991\"  \t\t\t from api_comparison where build_id = '$build1' AND \"request_name\" =~ /^$request_name$/), \t (SELECT mean(\"pct50\"::float) AS \"pct502\", mean(\"pct75\"::float) AS \"pct752\",      \t\t mean(\"pct90\"::float) AS \"pct902\", mean(\"pct95\"::float) AS \"pct952\", \t\t\t mean(\"pct99\"::float) AS \"pct992\"  \t\t\t from api_comparison where build_id = '$build2'  AND \"request_name\" =~ /^$request_name$/) ) GROUP BY request_name",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}