DISTRIBUTION=43-57
influx.port=8086
influx.host=ec2-54-87-82-65.compute-1.amazonaws.com
DURATION=30
VUSERS=8
RAMP_UP=80
test_name=circulation_checkIn
tenant=fs09000000
testType=fix_load
JVM_ARGS='-Xms1g -Xmx2g'
