#!groovy
ansiColor(colorMapName:'xterm') {node {
    currentBuild.displayName = "#${BUILD_NUMBER}-${params.teamName}-${params.Release_version}"
    withCredentials([[$class: 'AmazonWebServicesCredentialsBinding',
                        credentialsId: "stanislav_test",
                        accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                        secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']]) {
        stage('Checkout') {
            cleanWs disableDeferredWipeout: false, deleteDirs: true, cleanWhenAborted: true, cleanWhenFailure: true, cleanWhenSuccess: true
            checkout scm
        }
        dir('carrier-io/terraform') {
            docker.image('hashicorp/terraform:1.0.0').inside('-u 0:0 --entrypoint=') {
                stage('Plan') {
                    sh """
                        terraform init
                        terraform plan -input=false -out tfplan \
                            -var "key_pair_name=carrier-io-kp" \
                            -var "redis_password=1234567890" \
                            -var "influx_password=1234567890" \
                            -var "rabbit_password=1234567890"
                        """
                }
            }
        }
    }
}}